# These are supported funding model platforms

github: [Abhijeet999-beep]
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with your Community Bridge project-name e.g., rising-js-community
liberapay: # Replace with your Liberapay username
issuehunt: # Replace with your IssueHunt username
otechie: # Replace with your Otechie username
custom: # Replace with up to 4 custom sponsorship URLs, e.g., ['link1', 'link2']
