org.gradle.jvmargs=-Xmx4096M
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false


# 🔥 IMPORTANT (for compileSdk 36)
android.suppressUnsupportedCompileSdk=36

# ⚡ Optional but recommended (performance)
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true